# Generated by Django 3.0.5 on 2026-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
