# Generated by Django 3.0.5 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260313_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={'verbose_name': 'Hotel User'},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={'verbose_name': 'Hotel Vendor'},
        ),
        migrations.RemoveField(
            model_name='hotelvendor',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterModelTable(
            name='hoteluser',
            table='hotel_user',
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='hotel_vendor',
        ),
    ]
