# Generated by Django 3.0.5 on 2026-03-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260314_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel'},
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
    ]
