# Generated by Django 3.0.5 on 2026-03-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260315_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HotelVendor'),
        ),
    ]
