# Generated by Django 3.0.5 on 2026-03-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260315_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ameneties',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/amenities/'),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('price', models.FloatField()),
                ('booking_status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HotelUser')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'db_table': 'hotel_booking',
            },
        ),
    ]
