# Generated by Django 3.0.5 on 2026-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20260316_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
